apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
  labels:
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: gcr.io/terraform-project-367105/python-app
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name : my-python-app
          